#!/bin/bash

MYAPP=$(docker run \
        -v=$HOME/tmp/docker_django:/webapps/docker_django \
        -v=$HOME/tmp/docker_django/.docker/logs:/logs \
        -v=$HOME/tmp/docker_django/.docker/virtualenv/docker_django:/.virtualenvs/docker_django \
        -e=DJANGO_PROJECT_NAME=docker_django \
        -e=REPO_DIR_NAME=docker_django \
        -e=SETTINGS_FLAVOR=development \
        -e=NO_GUNICORN=true \
        -p=127.0.0.1:8000:80 \
        -i -t -d \
        douglasmiranda/gnginx1 /bin/bash);

printf 'Running on: %s\n' $MYAPP

# -e=NO_GUNICORN=true \
